### ISSUE TITLE
Doctrine doesn't recognize schema changes

### ISSUE THREAD

**Issue by smilesrg** [craue/CraueConfigBundle#30]
After setting up the bundle such commands as:

```
php app/console doctrine:migrations:diff
php app/console doctrine:migrations:migrate
php app/console doctrine:schema:update
```

doesn't recognize schema changes

**Comment by smilesrg** [comment]
Auto-mapping was turned off, so I had to define it manually in config:

```yml
# Doctrine Configuration
doctrine:
    orm:
        auto_mapping: false
        mappings:
            # ...
            CraueConfigBundle: ~
```
