### ISSUE TITLE
"Using a custom entity for settings" doesn't work

### ISSUE THREAD

**Issue by Sentence** [craue/CraueConfigBundle#43]
Doctrine doesn't recognite the changes with Symfony 3.4.6, so cannot change the value's type to text, like described in [here](https://github.com/craue/CraueConfigBundle#using-a-custom-entity-for-settings]).

**Comment by legumanP2T** [comment]
In symfony 4.4 the only way I found was:
parameters:
    craue_config.entity_name: App\Entity\MySetting

nor 
config:
    ...
nor
parameters:
    craue_config:
        entity_name: App\Entity\MySetting 

And it still want to create the craue_config_setting default table…

**Comment by LucaAnzaldo** [comment]
Create a file named 'craue_config.yaml' inside your "config/packages"-Folder.
Insert this:

```
craue_config:
  entity_name: App\Entity\YOURENTITY
```

After that, create you entity like this:

```
<?php

namespace App\Entity;

use Craue\ConfigBundle\Entity\BaseSetting;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Craue\ConfigBundle\Repository\SettingRepository")
 * @ORM\Table(name="app_configuration")
 */
class Configuration extends BaseSetting
{
}
```

You also have to create a file like "craue.yaml" inside your "config\routes"-Folder.

```
craue_config_settings_modify:
  path: /admin/settings/configuration
  defaults:
    _controller: Craue\ConfigBundle\Controller\SettingsController::modifyAction
```
