### ISSUE TITLE
Using a custom form schema

### ISSUE THREAD

**Issue by yvoloshin** [craue/CraueConfigBundle#46]
Hello,
I'm looking for a bit of help integrating a custom form schema. I'm trying to switch over from [SyliusSettingsBundle](https://github.com/Sylius/SyliusSettingsBundle) to CraueConfigBundle because Sylius doesn't support Symfony4. The settings fields need to be displayed in a custom form that was integrated with the Sylius bundle using a service tag in ``services.yml``, like this:
```
emails_settings_schema:
    class: AppBundle\Settings\EmailsSettingsSchema
    tags:
     - { name: "sylius.settings_schema", namespace: "emails" }
```
The schema was integrated using the [``findTaggedServices``](https://github.com/Sylius/SyliusSettingsBundle/blob/master/DependencyInjection/Compiler/RegisterSchemasPass.php) function in the bundle. Could you tell me how I can integrate this schema using CraueConfigBundle?
