### ISSUE TITLE
Doctrine Cache Provider in Symfony 4

### ISSUE THREAD

**Issue by shaunthornburgh** [craue/CraueConfigBundle#58]
Hi,

The configuration for using DoctrineCacheBundle seem to be for an older version of Symfony, please can you explain how to implement this in a Symfony 4 project?

```
# in app/config/config.yml
parameters:
  craue_config.cache_adapter.class: Craue\ConfigBundle\CacheAdapter\DoctrineCacheBundleAdapter

doctrine_cache:
  providers:
    craue_config_cache:
      apc: ~
      namespace: craue_config
      aliases:
        - craue_config_cache_provider
```
