### ISSUE TITLE
CraueConfigBundle, Redis and provider tagging

### ISSUE THREAD

**Issue by SergeiTPG** [craue/CraueConfigBundle#59]
When provider is tagged to be cleared during cache:clear command, container is failing to be assembled.
It appears, that assembling process messes up with arguments:

`"Symfony\Component\Cache\Traits\RedisTrait::init()" expects parameter 1 to be Redis, RedisArray, RedisCluster or Predis\ClientInterface, "string" given.`

With File cache adapter the same configuration works just fine.

```
    craue_config_cache_provider:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        public: false
        tags:
            - { name: 'cache.pool', clearer: 'cache.system_clearer' }
        arguments:
            - '@Redis'
            - 'craue_config'
            - 3600
```

**Comment by craue** [comment]
The problem is the `cache.pool` tag. According to the config shown, a `RedisAdapter` is registered as `craue_config_cache_provider` and tagged as a `cache.pool`. Symfony then changes its constructor arguments during container compilation, resulting in `RedisTrait::init()` receiving a string instead of a `Redis` object. If you add `provider: 'Redis'` to the tags, it should work:

```yaml
craue_config_cache_provider:
    class: Symfony\Component\Cache\Adapter\RedisAdapter
    public: false
    arguments:
        - '@Redis'
        - 'craue_config'
        - 3600
    tags:
        - {
            name: 'cache.pool',
            provider: 'Redis',
            namespace: 'craue_config',
            clearer: 'cache.system_clearer'
          }
```

Version 3.0.0 of this bundle simplifies the cache config:

```yaml
framework:
    cache:
        pools:
            craue_config_cache:
                adapter: cache.adapter.redis
                provider: Redis
```
